### ISSUE TITLE
use bash -c maybe leak chaild process

### ISSUE THREAD

**Issue by Asutorufa** [alfiankan/teleterm#23]
https://github.com/alfiankan/teleterm/blob/8d49ae757d3f9dfedbfb33b69ddbb11429ad3a76/executor/command.go#L19

if the bash exit, but child process is not exit, the child process will always running.

**Comment by alfiankan** [comment]
are u running long running processes? i think i need to make execution as queue worker what do u think?

so when we send command actually teleterm will dispatch new worker to execute sub process and get the output result and then send back to telegram

**Comment by Asutorufa** [comment]
I think add default timeout is a good choice, but the parent process is bash, when timeout reached the bash will exit, but the real process(child process) will not exit.
Maybe need kill all child process first, then kill bash.

**Comment by alfiankan** [comment]
i see i need to reproduce that, will update asap
