### ISSUE TITLE
Missmatch of file and erorr while try to build it

### ISSUE THREAD

**Issue by Burbonister** [alfiankan/teleterm#6]
**Describe the bug**
it doesnt have a lot of file and video does nat match and represtents the file are missing btw when i try to buid teleterm.go its sayng 
root@raspberrypi:~/terminal/teleterm/teleterm# go build -o teleterm4 teleterm.go
# command-line-arguments
./teleterm.go:6:15: syntax error: unexpected literal 5554722719, expecting )
./teleterm.go:7:26: syntax error: unexpected :, expecting comma or )

**To Reproduce**
1. Go to 'dev/teleterm/teleterm#'
2. Click on 'teleterm.go'
4. See error that 
-bash: ./1: Permission denied

**Desktop (please complete the following information):**
 - OS: [Rasbian ]
 - raspberry 3
 - Version [last ]

i realy like the idea what did u make but in rep it needs to fix it out

**Comment by alfiankan** [comment]
thanks for reposting issue @Burbonister, i will fix it ⚡️

**Comment by alfiankan** [comment]
teleterm v2 has been released, read new docs https://github.com/alfiankan/teleterm/blob/main/README.md
